export type SkillGroup = {
  title: string;
  items: string[];
};

export const skills: SkillGroup[] = [
  {
    title: "Scientific & Analytical",
    items: [
      "MATLAB",
      "GNU Plot",
      "QGIS",
      "ArcGIS",
      "Fortran",
      "IDL",
      "Python",
      "R",
      "SQL",
      "Data Analysis",
      "Data Visualisation",
      "Scientific Research",
      "Observational Astronomy",
    ],
  },
  {
    title: "Programming Languages",
    items: [
      "Python",
      "JavaScript",
      "TypeScript",
      "C++",
      "Java",
      "SQL",
      "HCL",
      "C#",
      "R",
      "HTML",
      "CSS",
      "Fortran",
      "IDL",
    ],
  },
  {
    title: "Frontend & Web",
    items: [
      "React",
      "Next.js",
      "Vite",
      "Tailwind CSS",
      "Three.js",
      "Motion",
      "Redux",
      "Material-UI",
      "HTML5",
      "CSS3",
      "Astro",
      "WordPress",
      "Drupal",
      "Figma",
      "Canva",
      "LaTeX",
    ],
  },
  {
    title: "Backend, Cloud & DevOps",
    items: [
      "Node.js",
      "Express.js",
      "FastAPI",
      "REST API",
      "MongoDB",
      "PostgreSQL",
      "MySQL",
      "Redis",
      "SQLite",
      "AWS",
      "Terraform",
      "Docker",
      "Ansible",
      "GitHub Actions",
      "Jenkins",
      "CI/CD Pipelines",
      "Blue-Green Deployment",
      "AWS CDK",
      "AWS Step Functions",
      "Infrastructure as Code",
      "Linux",
      "macOS",
      "UNIX Systems",
      "Git",
      "VS Code",
      "Postman",
      "API Integration",
    ],
  },
  {
    title: "AI, ML & Automation",
    items: [
      "AWS SageMaker",
      "AWS Bedrock",
      "Amazon Q",
      "TensorFlow",
      "PyTorch",
      "Scikit-learn",
      "Pandas",
      "NumPy",
      "LSTM / Neural Networks",
      "OpenCV / Image Processing",
      "Deep Learning",
      "MLOps",
      "LLM APIs",
      "RAG Pipelines",
      "Claude Code",
      "Kiro",
      "Cursor AI",
      "GitHub Copilot",
      "MCP Protocol",
      "AI Agent Frameworks",
      "Jupyter Notebook",
      "SonarQube",
    ],
  },
  {
    title: "Marketing & Analytics",
    items: [
      "Digital Marketing Strategy",
      "SEO",
      "Content Marketing",
      "Social Media Strategy",
      "Brand Strategy",
      "Lead Generation",
      "Inbound Marketing",
      "Campaign Planning",
      "B2B Marketing",
      "Audience Development",
      "Conversion Optimisation",
      "Growth Strategy",
      "Data-Driven Marketing",
      "Google Analytics 4 (GA4)",
      "Matomo Analytics",
      "Marketing Analytics",
      "KPI Tracking",
      "Dashboard Reporting",
      "SEO Analytics",
      "Campaign Measurement",
      "Hootsuite",
    ],
  },
  {
    title: "Communications & PR",
    items: [
      "Strategic Communications",
      "Science Communication",
      "Technical Writing",
      "Public Relations",
      "Media Relations",
      "Editorial Planning",
      "Press Release Writing",
      "Stakeholder Engagement",
      "Corporate Communications",
      "Event Communications",
      "Webinar Production",
      "Narrative Development",
      "Content Strategy",
      "Public Speaking",
      "Workshop Facilitation",
    ],
  },
  {
    title: "Space, Astronomy & Climate",
    items: [
      "Space Industry Communications",
      "Earth Observation",
      "Satellite Applications",
      "Space Policy Awareness",
      "ESA Business Applications",
      "Copernicus Programme",
      "Space Outreach",
      "Astronomy Communication",
      "Scientific Research Communication",
      "Space Innovation Ecosystems",
      "Climate Services from Space",
      "Space Entrepreneurship",
      "Climate Tech Communication",
      "Environmental Communication",
      "Climate Advocacy",
      "Net Zero Communication",
      "ESG Strategy",
      "Sustainability Reporting",
    ],
  },
  {
    title: "Delivery & Leadership",
    items: [
      "Project Management",
      "Programme Management",
      "Agile Methodologies",
      "Stakeholder Management",
      "Cross-functional Teams",
      "Workflow Optimisation",
      "Risk Management",
      "Sprint Planning",
      "Roadmapping",
      "OKR Planning",
      "Resource Allocation",
      "Team Leadership",
      "Strategic Leadership",
      "Organisational Development",
      "Change Management",
      "Partnership Development",
      "Mentoring",
      "Community Building",
      "Communication",
      "Problem Solving",
      "Critical Thinking",
      "Creativity",
      "Adaptability",
      "Collaboration",
      "Time Management",
      "Attention to Detail",
      "Analytical Thinking",
      "Teamwork",
    ],
  },
  {
    title: "Core CS",
    items: [
      "Data Structures & Algorithms",
      "Object-Oriented Programming",
      "Computer Networks",
      "Operating Systems",
      "Software Engineering",
      "Database Management Systems",
    ],
  },
  {
    title: "Interests",
    items: [
      "Full-Stack Development",
      "AI/ML Engineering",
      "DevOps & Cloud",
      "Open Source",
      "AI Agents & MCP",
      "Game Development",
    ],
  },
];
